### Register User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "firstName": "Demo",
    "lastName": "Obroy",
    "email": "demo@gmail.com",
    "password": "password123",
    "phone": "1234567890",
    "dateOfBirth": "2002-09-01",
    "role": "USER"
}
